[build-system]
requires = ["uv_build>=0.11.0,<1.0.0"]
build-backend = "uv_build"

[project]
name = "indico-toolkit"
description = "Indico Toolkit for Intake and Insights"
license = "MIT"
readme = "README.md"
urls = { source = "https://github.com/IndicoDelivery/indico-toolkit-python" }
requires-python = ">=3.11,<4"
version = "10.0.0"
dependencies = [
    "asyncstdlib (>=3.14.0,<4.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "tenacity (>=9.1.4,<10.0.0)",
]

[dependency-groups]
dev = [
    "coverage (>=7.0.0)",
    "poethepoet (>=0.30.0)",
    "pytest-asyncio (>=1.0.0)",
    "pytest-cov (>=7.0.0)",
    "pytest-mock (>=3.0.0)",
    "pytest (>=9.0.0)",
    "ruff (>=0.15.0)",
    "ty (>=0.0.50)",
]

[tool.poe.tasks]
coverage = "coverage html"
pytest = "pytest tests --cov=src --cov=tests"
ruff-check = "ruff check src tests"
ruff-fix = "ruff check --fix-only src tests"
ruff-format = "ruff format src tests"
ruff-format-check = "ruff format --check src tests"
ty = "ty check src tests"
ty-fix = "ty check --fix src tests"

format = ["ruff-fix", "ruff-format"]
check = ["ruff-check", "ruff-format-check", "ty"]
test = ["pytest", "coverage"]
all = ["format", "check", "test"]

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I"]
lint.fixable = ["I"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstractmethod"]
